/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class CardValidator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CardValidator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CardValidator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CardValidatorWrapperJNI.delete_CardValidator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_ValidationResultPtr validate(SWIGTYPE_p_CardPtr card) {
    return new SWIGTYPE_p_ValidationResultPtr(CardValidatorWrapperJNI.CardValidator_validate(swigCPtr, this, SWIGTYPE_p_CardPtr.getCPtr(card)), true);
  }

  public CardValidator() {
    this(CardValidatorWrapperJNI.new_CardValidator(), true);
  }

}
