/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class CardValidatorWrapperJNI {
  public final static native long CardValidator_validate(long jarg1, CardValidator jarg1_, long jarg2);
  public final static native long new_CardValidator();
  public final static native void delete_CardValidator(long jarg1);
}
