/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class CardWrapperJNI {
  public final static native long new_Card__SWIG_0(String jarg1, long jarg2, String jarg3, long jarg4);
  public final static native long new_Card__SWIG_1(String jarg1, long jarg2, String jarg3);
  public final static native long new_Card__SWIG_2(long jarg1, String jarg2, long jarg3);
  public final static native long new_Card__SWIG_3(long jarg1, long jarg2);
  public final static native long new_Card__SWIG_4();
  public final static native void Card_setName(long jarg1, Card jarg1_, String jarg2);
  public final static native String Card_name(long jarg1, Card jarg1_);
  public final static native long Card_profile__SWIG_0(long jarg1, Card jarg1_);
  public final static native void Card_resetProfile(long jarg1, Card jarg1_);
  public final static native void Card_setSystem(long jarg1, Card jarg1_, boolean jarg2);
  public final static native boolean Card_system(long jarg1, Card jarg1_);
  public final static native String Card_avatar(long jarg1, Card jarg1_);
  public final static native boolean Card_retail(long jarg1, Card jarg1_);
  public final static native void Card_setRetail(long jarg1, Card jarg1_, boolean jarg2);
  public final static native void Card_setType(long jarg1, Card jarg1_, String jarg2);
  public final static native String Card_type(long jarg1, Card jarg1_);
  public final static native String Card_accessType(long jarg1, Card jarg1_);
  public final static native void Card_setEncryptionKey(long jarg1, Card jarg1_, String jarg2);
  public final static native String Card_encryptionKey(long jarg1, Card jarg1_);
  public final static native String Card_getSearchCriteria(long jarg1, Card jarg1_);
  public final static native String Card_calculateModelHash(long jarg1, Card jarg1_);
  public final static native String Card_toJson(long jarg1, Card jarg1_);
  public final static native long Card_toJsonObj(long jarg1, Card jarg1_);
  public final static native boolean Card_equals(long jarg1, Card jarg1_, long jarg2, Card jarg2_);
  public final static native int Card_hashCode(long jarg1, Card jarg1_);
  public final static native long Card_build(long jarg1);
  public final static native long Card_fromJson__SWIG_0(String jarg1);
  public final static native long Card_fromJson__SWIG_1(long jarg1);
  public final static native boolean Card_contains(long jarg1, long jarg2);
  public final static native void delete_Card(long jarg1);
}
