/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class Card {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Card(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Card obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CardWrapperJNI.delete_Card(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Card(String uuid, SWIGTYPE_p_FieldList fields, String name, SWIGTYPE_p_ProfilePtr profile) {
    this(CardWrapperJNI.new_Card__SWIG_0(uuid, SWIGTYPE_p_FieldList.getCPtr(fields), name, SWIGTYPE_p_ProfilePtr.getCPtr(profile)), true);
  }

  public Card(String uuid, SWIGTYPE_p_FieldList fields, String name) {
    this(CardWrapperJNI.new_Card__SWIG_1(uuid, SWIGTYPE_p_FieldList.getCPtr(fields), name), true);
  }

  public Card(SWIGTYPE_p_FieldList fields, String name, SWIGTYPE_p_ProfilePtr profile) {
    this(CardWrapperJNI.new_Card__SWIG_2(SWIGTYPE_p_FieldList.getCPtr(fields), name, SWIGTYPE_p_ProfilePtr.getCPtr(profile)), true);
  }

  public Card(SWIGTYPE_p_std__shared_ptrT_Card_t card, SWIGTYPE_p_FieldList fields) {
    this(CardWrapperJNI.new_Card__SWIG_3(SWIGTYPE_p_std__shared_ptrT_Card_t.getCPtr(card), SWIGTYPE_p_FieldList.getCPtr(fields)), true);
  }

  public Card() {
    this(CardWrapperJNI.new_Card__SWIG_4(), true);
  }

  public void setName(String name) {
    CardWrapperJNI.Card_setName(swigCPtr, this, name);
  }

  public String name() {
    return CardWrapperJNI.Card_name(swigCPtr, this);
  }

  public SWIGTYPE_p_ProfilePtr profile() {
    return new SWIGTYPE_p_ProfilePtr(CardWrapperJNI.Card_profile__SWIG_0(swigCPtr, this), true);
  }

  public void resetProfile() {
    CardWrapperJNI.Card_resetProfile(swigCPtr, this);
  }

  public void setSystem(boolean system) {
    CardWrapperJNI.Card_setSystem(swigCPtr, this, system);
  }

  public boolean system() {
    return CardWrapperJNI.Card_system(swigCPtr, this);
  }

  public String avatar() {
    return CardWrapperJNI.Card_avatar(swigCPtr, this);
  }

  public boolean retail() {
    return CardWrapperJNI.Card_retail(swigCPtr, this);
  }

  public void setRetail(boolean retail) {
    CardWrapperJNI.Card_setRetail(swigCPtr, this, retail);
  }

  public void setType(String type) {
    CardWrapperJNI.Card_setType(swigCPtr, this, type);
  }

  public String type() {
    return CardWrapperJNI.Card_type(swigCPtr, this);
  }

  public String accessType() {
    return CardWrapperJNI.Card_accessType(swigCPtr, this);
  }

  public void setEncryptionKey(String value) {
    CardWrapperJNI.Card_setEncryptionKey(swigCPtr, this, value);
  }

  public String encryptionKey() {
    return CardWrapperJNI.Card_encryptionKey(swigCPtr, this);
  }

  public String getSearchCriteria() {
    return CardWrapperJNI.Card_getSearchCriteria(swigCPtr, this);
  }

  public String calculateModelHash() {
    return CardWrapperJNI.Card_calculateModelHash(swigCPtr, this);
  }

  public String toJson() {
    return CardWrapperJNI.Card_toJson(swigCPtr, this);
  }

  public SWIGTYPE_p_json11__Json toJsonObj() {
    return new SWIGTYPE_p_json11__Json(CardWrapperJNI.Card_toJsonObj(swigCPtr, this), true);
  }

  public boolean equals(Card other) {
    return CardWrapperJNI.Card_equals(swigCPtr, this, Card.getCPtr(other), other);
  }

  public int hashCode() {
    return CardWrapperJNI.Card_hashCode(swigCPtr, this);
  }

  public static SWIGTYPE_p_std__shared_ptrT_Card_t build(SWIGTYPE_p_ProfilePtr profile) {
    return new SWIGTYPE_p_std__shared_ptrT_Card_t(CardWrapperJNI.Card_build(SWIGTYPE_p_ProfilePtr.getCPtr(profile)), true);
  }

  public static SWIGTYPE_p_std__shared_ptrT_Card_t fromJson(String jsonString) {
    return new SWIGTYPE_p_std__shared_ptrT_Card_t(CardWrapperJNI.Card_fromJson__SWIG_0(jsonString), true);
  }

  public static SWIGTYPE_p_std__shared_ptrT_Card_t fromJson(SWIGTYPE_p_json11__Json jsonObj) {
    return new SWIGTYPE_p_std__shared_ptrT_Card_t(CardWrapperJNI.Card_fromJson__SWIG_1(SWIGTYPE_p_json11__Json.getCPtr(jsonObj)), true);
  }

  public static boolean contains(SWIGTYPE_p_std__listT_std__shared_ptrT_Card_t_t items, SWIGTYPE_p_std__shared_ptrT_Card_t item) {
    return CardWrapperJNI.Card_contains(SWIGTYPE_p_std__listT_std__shared_ptrT_Card_t_t.getCPtr(items), SWIGTYPE_p_std__shared_ptrT_Card_t.getCPtr(item));
  }

}
