/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ContactHelperWrapperJNI {
  public final static native long addNickname(long jarg1, long jarg2);
  public final static native String getAvatar(long jarg1, long jarg2);
  public final static native long addCards(long jarg1, long jarg2);
  public final static native void refreshConflicts(long jarg1);
  public final static native long addConflict(long jarg1, String jarg2);
  public final static native boolean isMatchByMobile(long jarg1, long jarg2);
  public final static native boolean isMatchByEmail(long jarg1, long jarg2);
  public final static native boolean isMatchByPrivVar(long jarg1, long jarg2);
  public final static native boolean isSameCardOwner(long jarg1, long jarg2);
  public final static native boolean isMatchByName(long jarg1, long jarg2);
  public final static native boolean isMatchByVarSubset(long jarg1, long jarg2);
  public final static native boolean fieldsAreSubset(long jarg1, long jarg2);
}
