/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ContactHelperWrapper {
  public static SWIGTYPE_p_ContactPtr addNickname(SWIGTYPE_p_ContactPtr fromContact, SWIGTYPE_p_ContactPtr toContact) {
    return new SWIGTYPE_p_ContactPtr(ContactHelperWrapperJNI.addNickname(SWIGTYPE_p_ContactPtr.getCPtr(fromContact), SWIGTYPE_p_ContactPtr.getCPtr(toContact)), true);
  }

  public static String getAvatar(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_CardList cards) {
    return ContactHelperWrapperJNI.getAvatar(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_CardList.getCPtr(cards));
  }

  public static SWIGTYPE_p_ContactPtr addCards(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_CardList cards) {
    return new SWIGTYPE_p_ContactPtr(ContactHelperWrapperJNI.addCards(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_CardList.getCPtr(cards)), true);
  }

  public static void refreshConflicts(SWIGTYPE_p_ContactPtr contact) {
    ContactHelperWrapperJNI.refreshConflicts(SWIGTYPE_p_ContactPtr.getCPtr(contact));
  }

  public static SWIGTYPE_p_ContactPtr addConflict(SWIGTYPE_p_ContactPtr contact, String conflictType) {
    return new SWIGTYPE_p_ContactPtr(ContactHelperWrapperJNI.addConflict(SWIGTYPE_p_ContactPtr.getCPtr(contact), conflictType), true);
  }

  public static boolean isMatchByMobile(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_ContactPtr compareWith) {
    return ContactHelperWrapperJNI.isMatchByMobile(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_ContactPtr.getCPtr(compareWith));
  }

  public static boolean isMatchByEmail(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_ContactPtr compareWith) {
    return ContactHelperWrapperJNI.isMatchByEmail(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_ContactPtr.getCPtr(compareWith));
  }

  public static boolean isMatchByPrivVar(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_ContactPtr compareWith) {
    return ContactHelperWrapperJNI.isMatchByPrivVar(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_ContactPtr.getCPtr(compareWith));
  }

  public static boolean isSameCardOwner(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_ContactPtr compareWith) {
    return ContactHelperWrapperJNI.isSameCardOwner(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_ContactPtr.getCPtr(compareWith));
  }

  public static boolean isMatchByName(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_ContactPtr compareWith) {
    return ContactHelperWrapperJNI.isMatchByName(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_ContactPtr.getCPtr(compareWith));
  }

  public static boolean isMatchByVarSubset(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_ContactPtr compareWith) {
    return ContactHelperWrapperJNI.isMatchByVarSubset(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_ContactPtr.getCPtr(compareWith));
  }

  public static boolean fieldsAreSubset(SWIGTYPE_p_FieldList left, SWIGTYPE_p_FieldList right) {
    return ContactHelperWrapperJNI.fieldsAreSubset(SWIGTYPE_p_FieldList.getCPtr(left), SWIGTYPE_p_FieldList.getCPtr(right));
  }

}
