/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ContactWrapperJNI {
  public final static native long new_Contact__SWIG_0(String jarg1, long jarg2, long jarg3, String jarg4, long jarg5);
  public final static native long new_Contact__SWIG_1(long jarg1, long jarg2, String jarg3, long jarg4);
  public final static native long new_Contact__SWIG_2();
  public final static native long Contact_conflicts(long jarg1, Contact jarg1_);
  public final static native void Contact_conflictsRemove(long jarg1, Contact jarg1_, String jarg2);
  public final static native void Contact_conflictsAdd__SWIG_0(long jarg1, Contact jarg1_, String jarg2);
  public final static native void Contact_conflictsAdd__SWIG_1(long jarg1, Contact jarg1_, long jarg2);
  public final static native String Contact_pathToAvatar(long jarg1, Contact jarg1_);
  public final static native void Contact_setPathToAvatar(long jarg1, Contact jarg1_, String jarg2);
  public final static native long Contact_cards(long jarg1, Contact jarg1_);
  public final static native void Contact_addCards(long jarg1, Contact jarg1_, long jarg2);
  public final static native void Contact_addCard(long jarg1, Contact jarg1_, long jarg2);
  public final static native void Contact_clearCards(long jarg1, Contact jarg1_);
  public final static native void Contact_removeCards(long jarg1, Contact jarg1_, long jarg2);
  public final static native void Contact_setMergedInUuid(long jarg1, Contact jarg1_, String jarg2);
  public final static native String Contact_mergedInUuid(long jarg1, Contact jarg1_);
  public final static native void Contact_mergedWithUuidsAdd(long jarg1, Contact jarg1_, String jarg2);
  public final static native long Contact_mergedWithUuids(long jarg1, Contact jarg1_);
  public final static native long Contact_groupNames(long jarg1, Contact jarg1_);
  public final static native void Contact_groupNamesAdd(long jarg1, Contact jarg1_, long jarg2);
  public final static native void Contact_addGroupName(long jarg1, Contact jarg1_, String jarg2);
  public final static native void Contact_setRetail(long jarg1, Contact jarg1_, boolean jarg2);
  public final static native boolean Contact_retail(long jarg1, Contact jarg1_);
  public final static native void Contact_setPhoneBookUuid(long jarg1, Contact jarg1_, String jarg2);
  public final static native String Contact_phoneBookUuid(long jarg1, Contact jarg1_);
  public final static native void Contact_sharedCardsUuidAdd(long jarg1, Contact jarg1_, long jarg2);
  public final static native long Contact_sharedCardsUuid(long jarg1, Contact jarg1_);
  public final static native String Contact_createdDate(long jarg1, Contact jarg1_);
  public final static native void Contact_setCreatedDate(long jarg1, Contact jarg1_, String jarg2);
  public final static native String Contact_longitude(long jarg1, Contact jarg1_);
  public final static native void Contact_setLongitude(long jarg1, Contact jarg1_, String jarg2);
  public final static native String Contact_latitude(long jarg1, Contact jarg1_);
  public final static native void Contact_setLatitude(long jarg1, Contact jarg1_, String jarg2);
  public final static native long Contact_potentialMatchProfiles(long jarg1, Contact jarg1_);
  public final static native void Contact_potentialMatchProfilesRemove(long jarg1, Contact jarg1_, long jarg2);
  public final static native void Contact_potentialMatchProfilesAdd(long jarg1, Contact jarg1_, long jarg2);
  public final static native void Contact_setCloudVerified(long jarg1, Contact jarg1_, boolean jarg2);
  public final static native boolean Contact_cloudVerified(long jarg1, Contact jarg1_);
  public final static native long Contact_potentialVars(long jarg1, Contact jarg1_);
  public final static native void Contact_potentialVarsRemove(long jarg1, Contact jarg1_, String jarg2);
  public final static native void Contact_setPotentialVars(long jarg1, Contact jarg1_, long jarg2);
  public final static native void Contact_potentialVarsAdd(long jarg1, Contact jarg1_, String jarg2, String jarg3);
  public final static native void Contact_setName(long jarg1, Contact jarg1_, String jarg2);
  public final static native String Contact_name(long jarg1, Contact jarg1_);
  public final static native void Contact_setAccountType(long jarg1, Contact jarg1_, String jarg2);
  public final static native void Contact_setPublicKey(long jarg1, Contact jarg1_, String jarg2);
  public final static native void Contact_setProfileUuid(long jarg1, Contact jarg1_, String jarg2);
  public final static native long Contact_ignoredMatchProfileUuids(long jarg1, Contact jarg1_);
  public final static native void Contact_setBackupId(long jarg1, Contact jarg1_, String jarg2);
  public final static native String Contact_backupId(long jarg1, Contact jarg1_);
  public final static native String Contact_calculateModelHash(long jarg1, Contact jarg1_);
  public final static native String Contact_toJson(long jarg1, Contact jarg1_);
  public final static native long Contact_toJsonObj(long jarg1, Contact jarg1_);
  public final static native long Contact_build();
  public final static native long Contact_fromJson__SWIG_0(String jarg1);
  public final static native long Contact_fromJson__SWIG_1(long jarg1);
  public final static native void Contact_setImportStatus(long jarg1, Contact jarg1_, String jarg2);
  public final static native String Contact_importStatus(long jarg1, Contact jarg1_);
  public final static native boolean Contact_contains(long jarg1, long jarg2);
  public final static native void Contact_remove__SWIG_0(long jarg1, long jarg2);
  public final static native boolean Contact_remove__SWIG_1(long jarg1, long jarg2);
  public final static native long Contact_allFields(long jarg1, Contact jarg1_);
  public final static native void delete_Contact(long jarg1);
}
