/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ContactMergeServiceWrapper {
  public static SWIGTYPE_p_ContactPtr merge(SWIGTYPE_p_ContactList contacts) {
    return new SWIGTYPE_p_ContactPtr(ContactMergeServiceWrapperJNI.merge__SWIG_0(SWIGTYPE_p_ContactList.getCPtr(contacts)), true);
  }

  public static String getNotBlank(String string1, String string2) {
    return ContactMergeServiceWrapperJNI.getNotBlank(string1, string2);
  }

  public static SWIGTYPE_p_ContactList mergeWithCards(SWIGTYPE_p_ContactList contacts) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.mergeWithCards__SWIG_0(SWIGTYPE_p_ContactList.getCPtr(contacts)), true);
  }

  public static SWIGTYPE_p_ContactList mergeWithCards(SWIGTYPE_p_ContactList contacts, boolean initialMerge) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.mergeWithCards__SWIG_1(SWIGTYPE_p_ContactList.getCPtr(contacts), initialMerge), true);
  }

  public static SWIGTYPE_p_ContactList initialProcess(SWIGTYPE_p_ContactList contacts) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.initialProcess(SWIGTYPE_p_ContactList.getCPtr(contacts)), true);
  }

  public static SWIGTYPE_p_ContactList applyCardsOutdated(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_CardList cards, SWIGTYPE_p_ContactList linkedContacts) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.applyCardsOutdated(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_CardList.getCPtr(cards), SWIGTYPE_p_ContactList.getCPtr(linkedContacts)), true);
  }

  public static SWIGTYPE_p_ContactList applyCards(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_CardList cards, SWIGTYPE_p_ContactList linkedContacts) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.applyCards(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_CardList.getCPtr(cards), SWIGTYPE_p_ContactList.getCPtr(linkedContacts)), true);
  }

  public static SWIGTYPE_p_ContactList applyCardsInner(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_CardList cards, SWIGTYPE_p_ContactList linkedContacts) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.applyCardsInner(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_CardList.getCPtr(cards), SWIGTYPE_p_ContactList.getCPtr(linkedContacts)), true);
  }

  public static SWIGTYPE_p_ContactList mergeByOutdated(SWIGTYPE_p_FieldPtr outdatedVar, SWIGTYPE_p_ContactList contacts, SWIGTYPE_p_CardList cards) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.mergeByOutdated(SWIGTYPE_p_FieldPtr.getCPtr(outdatedVar), SWIGTYPE_p_ContactList.getCPtr(contacts), SWIGTYPE_p_CardList.getCPtr(cards)), true);
  }

  public static SWIGTYPE_p_ContactList merge(SWIGTYPE_p_ContactList contacts, SWIGTYPE_p_CardList cards) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.merge__SWIG_1(SWIGTYPE_p_ContactList.getCPtr(contacts), SWIGTYPE_p_CardList.getCPtr(cards)), true);
  }

  public static SWIGTYPE_p_ContactList mergeInner(SWIGTYPE_p_FieldPtr outdatedVar, SWIGTYPE_p_ContactList contacts, SWIGTYPE_p_CardList cards) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.mergeInner(SWIGTYPE_p_FieldPtr.getCPtr(outdatedVar), SWIGTYPE_p_ContactList.getCPtr(contacts), SWIGTYPE_p_CardList.getCPtr(cards)), true);
  }

  public static SWIGTYPE_p_ContactPtr merge(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_CardPtr card) {
    return new SWIGTYPE_p_ContactPtr(ContactMergeServiceWrapperJNI.merge__SWIG_2(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_CardPtr.getCPtr(card)), true);
  }

  public static SWIGTYPE_p_ContactPtr merge(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_CardList cardsToMerge) {
    return new SWIGTYPE_p_ContactPtr(ContactMergeServiceWrapperJNI.merge__SWIG_3(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_CardList.getCPtr(cardsToMerge)), true);
  }

  public static SWIGTYPE_p_CardPtr mergeCards(SWIGTYPE_p_CardList cards) {
    return new SWIGTYPE_p_CardPtr(ContactMergeServiceWrapperJNI.mergeCards(SWIGTYPE_p_CardList.getCPtr(cards)), true);
  }

  public static SWIGTYPE_p_ContactList findLinkedContacts(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_std__listT_std__pairT_CardPtr_ContactPtr_t_t cardsToContact) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.findLinkedContacts(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_std__listT_std__pairT_CardPtr_ContactPtr_t_t.getCPtr(cardsToContact)), true);
  }

  public static SWIGTYPE_p_ContactList findLinkedContactsByVars(SWIGTYPE_p_ContactList contacts, SWIGTYPE_p_std__unordered_mapT_std__string_FieldList_t allVars, SWIGTYPE_p_ContactList allContacts) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.findLinkedContactsByVars(SWIGTYPE_p_ContactList.getCPtr(contacts), SWIGTYPE_p_std__unordered_mapT_std__string_FieldList_t.getCPtr(allVars), SWIGTYPE_p_ContactList.getCPtr(allContacts)), true);
  }

  public static boolean isMatchByPrivateVar(SWIGTYPE_p_CardPtr card, SWIGTYPE_p_ContactPtr contact) {
    return ContactMergeServiceWrapperJNI.isMatchByPrivateVar(SWIGTYPE_p_CardPtr.getCPtr(card), SWIGTYPE_p_ContactPtr.getCPtr(contact));
  }

  public static boolean isMatchByPseudoVar(SWIGTYPE_p_CardPtr card, SWIGTYPE_p_ContactPtr contact) {
    return ContactMergeServiceWrapperJNI.isMatchByPseudoVar(SWIGTYPE_p_CardPtr.getCPtr(card), SWIGTYPE_p_ContactPtr.getCPtr(contact));
  }

  public static boolean isMatchByOutdatedVar(SWIGTYPE_p_CardPtr card, SWIGTYPE_p_FieldPtr outdatedVar, SWIGTYPE_p_ContactPtr contact) {
    return ContactMergeServiceWrapperJNI.isMatchByOutdatedVar(SWIGTYPE_p_CardPtr.getCPtr(card), SWIGTYPE_p_FieldPtr.getCPtr(outdatedVar), SWIGTYPE_p_ContactPtr.getCPtr(contact));
  }

  public static SWIGTYPE_p_ContactList split(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_std__listT_CardList_t cards) {
    return new SWIGTYPE_p_ContactList(ContactMergeServiceWrapperJNI.split(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_std__listT_CardList_t.getCPtr(cards)), true);
  }

  public static SWIGTYPE_p_ContactPtr potentialMatch(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_CardList cards) {
    return new SWIGTYPE_p_ContactPtr(ContactMergeServiceWrapperJNI.potentialMatch(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_CardList.getCPtr(cards)), true);
  }

  public static SWIGTYPE_p_ContactPtr outdatedMatch(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_FieldPtr outdatedVar, SWIGTYPE_p_CardList cards) {
    return new SWIGTYPE_p_ContactPtr(ContactMergeServiceWrapperJNI.outdatedMatch(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_FieldPtr.getCPtr(outdatedVar), SWIGTYPE_p_CardList.getCPtr(cards)), true);
  }

  public static SWIGTYPE_p_ContactPtr copyFieldsFrom(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_CardPtr card) {
    return new SWIGTYPE_p_ContactPtr(ContactMergeServiceWrapperJNI.copyFieldsFrom(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_CardPtr.getCPtr(card)), true);
  }

  public static void updateConflicts(SWIGTYPE_p_ContactList contacts) {
    ContactMergeServiceWrapperJNI.updateConflicts(SWIGTYPE_p_ContactList.getCPtr(contacts));
  }

}
