/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ContactImportServiceWrapper {
  public static SWIGTYPE_p_ContactImportResult importOne(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_ContactList stateContacts, boolean withHashCheck, SWIGTYPE_p_StringList countryCodes) {
    return new SWIGTYPE_p_ContactImportResult(ContactImportServiceWrapperJNI.importOne__SWIG_0(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_ContactList.getCPtr(stateContacts), withHashCheck, SWIGTYPE_p_StringList.getCPtr(countryCodes)), true);
  }

  public static SWIGTYPE_p_ContactImportResult importOne(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_ContactList stateContacts, boolean withHashCheck) {
    return new SWIGTYPE_p_ContactImportResult(ContactImportServiceWrapperJNI.importOne__SWIG_1(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_ContactList.getCPtr(stateContacts), withHashCheck), true);
  }

  public static SWIGTYPE_p_ContactImportResult importOne(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_ContactList stateContacts) {
    return new SWIGTYPE_p_ContactImportResult(ContactImportServiceWrapperJNI.importOne__SWIG_2(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_ContactList.getCPtr(stateContacts)), true);
  }

  public static SWIGTYPE_p_ContactImportResult importAll(SWIGTYPE_p_ContactList contacts, SWIGTYPE_p_ContactList stateContacts, boolean withHashCheck, SWIGTYPE_p_StringList countryCodes) {
    return new SWIGTYPE_p_ContactImportResult(ContactImportServiceWrapperJNI.importAll__SWIG_0(SWIGTYPE_p_ContactList.getCPtr(contacts), SWIGTYPE_p_ContactList.getCPtr(stateContacts), withHashCheck, SWIGTYPE_p_StringList.getCPtr(countryCodes)), true);
  }

  public static SWIGTYPE_p_ContactImportResult importAll(SWIGTYPE_p_ContactList contacts, SWIGTYPE_p_ContactList stateContacts, boolean withHashCheck) {
    return new SWIGTYPE_p_ContactImportResult(ContactImportServiceWrapperJNI.importAll__SWIG_1(SWIGTYPE_p_ContactList.getCPtr(contacts), SWIGTYPE_p_ContactList.getCPtr(stateContacts), withHashCheck), true);
  }

  public static SWIGTYPE_p_ContactList filterByHash(SWIGTYPE_p_ContactList contacts, SWIGTYPE_p_ContactList importedContacts) {
    return new SWIGTYPE_p_ContactList(ContactImportServiceWrapperJNI.filterByHash(SWIGTYPE_p_ContactList.getCPtr(contacts), SWIGTYPE_p_ContactList.getCPtr(importedContacts)), true);
  }

  public static SWIGTYPE_p_std__pairT_ContactList_ContactList_t _import(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_ContactList importedContacts, SWIGTYPE_p_ContactList mergedContacts, SWIGTYPE_p_std__mapT_Field_const_p_StringList_t allVars) {
    return new SWIGTYPE_p_std__pairT_ContactList_ContactList_t(ContactImportServiceWrapperJNI._import(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_ContactList.getCPtr(importedContacts), SWIGTYPE_p_ContactList.getCPtr(mergedContacts), SWIGTYPE_p_std__mapT_Field_const_p_StringList_t.getCPtr(allVars)), true);
  }

  public static void mergeContacts(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_ContactPtr stateContact, SWIGTYPE_p_ContactList mergedWithContacts, SWIGTYPE_p_std__mapT_Field_const_p_StringList_t allVars) {
    ContactImportServiceWrapperJNI.mergeContacts(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_ContactPtr.getCPtr(stateContact), SWIGTYPE_p_ContactList.getCPtr(mergedWithContacts), SWIGTYPE_p_std__mapT_Field_const_p_StringList_t.getCPtr(allVars));
  }

  public static SWIGTYPE_p_Groups createGroups(SWIGTYPE_p_ContactList contacts) {
    return new SWIGTYPE_p_Groups(ContactImportServiceWrapperJNI.createGroups(SWIGTYPE_p_ContactList.getCPtr(contacts)), true);
  }

}
