/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ContactValidator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ContactValidator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContactValidator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContactValidatorWrapperJNI.delete_ContactValidator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_ValidationResultPtr validate(SWIGTYPE_p_ContactPtr value) {
    return new SWIGTYPE_p_ValidationResultPtr(ContactValidatorWrapperJNI.ContactValidator_validate(swigCPtr, this, SWIGTYPE_p_ContactPtr.getCPtr(value)), true);
  }

  public SWIGTYPE_p_FieldsValidatorResultPtr validatePair(SWIGTYPE_p_ContactPtr originalContact, SWIGTYPE_p_ContactPtr modifiedContact) {
    return new SWIGTYPE_p_FieldsValidatorResultPtr(ContactValidatorWrapperJNI.ContactValidator_validatePair(swigCPtr, this, SWIGTYPE_p_ContactPtr.getCPtr(originalContact), SWIGTYPE_p_ContactPtr.getCPtr(modifiedContact)), true);
  }

  public ContactValidator() {
    this(ContactValidatorWrapperJNI.new_ContactValidator(), true);
  }

}
