/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ContactImportServiceWrapperJNI {
  public final static native long importOne__SWIG_0(long jarg1, long jarg2, boolean jarg3, long jarg4);
  public final static native long importOne__SWIG_1(long jarg1, long jarg2, boolean jarg3);
  public final static native long importOne__SWIG_2(long jarg1, long jarg2);
  public final static native long importAll__SWIG_0(long jarg1, long jarg2, boolean jarg3, long jarg4);
  public final static native long importAll__SWIG_1(long jarg1, long jarg2, boolean jarg3);
  public final static native long filterByHash(long jarg1, long jarg2);
  public final static native long _import(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native void mergeContacts(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long createGroups(long jarg1);
}
