/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ContactImportResultWrapperJNI {
  public final static native long new_ContactImportResult__SWIG_0();
  public final static native long new_ContactImportResult__SWIG_1(long jarg1, long jarg2);
  public final static native long ContactImportResult_contacts(long jarg1, ContactImportResult jarg1_);
  public final static native long ContactImportResult_groups(long jarg1, ContactImportResult jarg1_);
  public final static native void delete_ContactImportResult(long jarg1);
}
