/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ContactMergeServiceWrapperJNI {
  public final static native long merge__SWIG_0(long jarg1);
  public final static native String getNotBlank(String jarg1, String jarg2);
  public final static native long mergeWithCards__SWIG_0(long jarg1);
  public final static native long mergeWithCards__SWIG_1(long jarg1, boolean jarg2);
  public final static native long initialProcess(long jarg1);
  public final static native long applyCardsOutdated(long jarg1, long jarg2, long jarg3);
  public final static native long applyCards(long jarg1, long jarg2, long jarg3);
  public final static native long applyCardsInner(long jarg1, long jarg2, long jarg3);
  public final static native long mergeByOutdated(long jarg1, long jarg2, long jarg3);
  public final static native long merge__SWIG_1(long jarg1, long jarg2);
  public final static native long mergeInner(long jarg1, long jarg2, long jarg3);
  public final static native long merge__SWIG_2(long jarg1, long jarg2);
  public final static native long merge__SWIG_3(long jarg1, long jarg2);
  public final static native long mergeCards(long jarg1);
  public final static native long findLinkedContacts(long jarg1, long jarg2);
  public final static native long findLinkedContactsByVars(long jarg1, long jarg2, long jarg3);
  public final static native boolean isMatchByPrivateVar(long jarg1, long jarg2);
  public final static native boolean isMatchByPseudoVar(long jarg1, long jarg2);
  public final static native boolean isMatchByOutdatedVar(long jarg1, long jarg2, long jarg3);
  public final static native long split(long jarg1, long jarg2);
  public final static native long potentialMatch(long jarg1, long jarg2);
  public final static native long outdatedMatch(long jarg1, long jarg2, long jarg3);
  public final static native long copyFieldsFrom(long jarg1, long jarg2);
  public final static native void updateConflicts(long jarg1);
}
