/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class CountryCodeResolverWrapperJNI {
  public final static native long new_CountryCodeResolveChanges__SWIG_0();
  public final static native long new_CountryCodeResolveChanges__SWIG_1(long jarg1, long jarg2);
  public final static native void CountryCodeResolveChanges_oldFieldsValuesAdd(long jarg1, CountryCodeResolveChanges jarg1_, String jarg2);
  public final static native void CountryCodeResolveChanges_resolvedFieldsValuesAdd(long jarg1, CountryCodeResolveChanges jarg1_, String jarg2);
  public final static native void delete_CountryCodeResolveChanges(long jarg1);
  public final static native long new_CountryCodeResolveResult(long jarg1, long jarg2, CountryCodeResolveChanges jarg2_);
  public final static native void delete_CountryCodeResolveResult(long jarg1);
  public final static native long ignoreAllConflicts(long jarg1);
  public final static native long ignoreConflict(long jarg1);
  public final static native long resolve(long jarg1, String jarg2, long jarg3);
  public final static native String applyCountryCode(String jarg1, String jarg2);
  public final static native void checkCountryCodeConflict(long jarg1, long jarg2);
}
