/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class CountryCodeResolveChanges {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CountryCodeResolveChanges(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CountryCodeResolveChanges obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CountryCodeResolverWrapperJNI.delete_CountryCodeResolveChanges(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CountryCodeResolveChanges() {
    this(CountryCodeResolverWrapperJNI.new_CountryCodeResolveChanges__SWIG_0(), true);
  }

  public CountryCodeResolveChanges(SWIGTYPE_p_StringList resolvedFieldsValues, SWIGTYPE_p_StringList oldFieldsValues) {
    this(CountryCodeResolverWrapperJNI.new_CountryCodeResolveChanges__SWIG_1(SWIGTYPE_p_StringList.getCPtr(resolvedFieldsValues), SWIGTYPE_p_StringList.getCPtr(oldFieldsValues)), true);
  }

  public void oldFieldsValuesAdd(String value) {
    CountryCodeResolverWrapperJNI.CountryCodeResolveChanges_oldFieldsValuesAdd(swigCPtr, this, value);
  }

  public void resolvedFieldsValuesAdd(String value) {
    CountryCodeResolverWrapperJNI.CountryCodeResolveChanges_resolvedFieldsValuesAdd(swigCPtr, this, value);
  }

}
