/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class CountryCodeResolveResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CountryCodeResolveResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CountryCodeResolveResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CountryCodeResolverWrapperJNI.delete_CountryCodeResolveResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CountryCodeResolveResult(SWIGTYPE_p_ContactList contacts, CountryCodeResolveChanges fieldsChanges) {
    this(CountryCodeResolverWrapperJNI.new_CountryCodeResolveResult(SWIGTYPE_p_ContactList.getCPtr(contacts), CountryCodeResolveChanges.getCPtr(fieldsChanges), fieldsChanges), true);
  }

}
