/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class CountryCodeResolverWrapper {
  public static SWIGTYPE_p_ContactList ignoreAllConflicts(SWIGTYPE_p_ContactList contacts) {
    return new SWIGTYPE_p_ContactList(CountryCodeResolverWrapperJNI.ignoreAllConflicts(SWIGTYPE_p_ContactList.getCPtr(contacts)), true);
  }

  public static SWIGTYPE_p_ContactPtr ignoreConflict(SWIGTYPE_p_ContactPtr contact) {
    return new SWIGTYPE_p_ContactPtr(CountryCodeResolverWrapperJNI.ignoreConflict(SWIGTYPE_p_ContactPtr.getCPtr(contact)), true);
  }

  public static CountryCodeResolveResult resolve(SWIGTYPE_p_ContactList contacts, String countryCode, SWIGTYPE_p_StringList possibleCountryCodes) {
    return new CountryCodeResolveResult(CountryCodeResolverWrapperJNI.resolve(SWIGTYPE_p_ContactList.getCPtr(contacts), countryCode, SWIGTYPE_p_StringList.getCPtr(possibleCountryCodes)), true);
  }

  public static String applyCountryCode(String phone, String code) {
    return CountryCodeResolverWrapperJNI.applyCountryCode(phone, code);
  }

  public static void checkCountryCodeConflict(SWIGTYPE_p_ContactPtr contact, SWIGTYPE_p_StringList possibleCountryCodes) {
    CountryCodeResolverWrapperJNI.checkCountryCodeConflict(SWIGTYPE_p_ContactPtr.getCPtr(contact), SWIGTYPE_p_StringList.getCPtr(possibleCountryCodes));
  }

}
