/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class DetailedValidationResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DetailedValidationResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DetailedValidationResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ValidationResultWrapperJNI.delete_DetailedValidationResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    ValidationResultWrapperJNI.DetailedValidationResult_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return ValidationResultWrapperJNI.DetailedValidationResult_name_get(swigCPtr, this);
  }

  public void setResult(SWIGTYPE_p_std__shared_ptrT_ValidationResult_t value) {
    ValidationResultWrapperJNI.DetailedValidationResult_result_set(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_ValidationResult_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__shared_ptrT_ValidationResult_t getResult() {
    long cPtr = ValidationResultWrapperJNI.DetailedValidationResult_result_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__shared_ptrT_ValidationResult_t(cPtr, false);
  }

  public DetailedValidationResult() {
    this(ValidationResultWrapperJNI.new_DetailedValidationResult__SWIG_0(), true);
  }

  public DetailedValidationResult(String n, SWIGTYPE_p_std__shared_ptrT_ValidationResult_t r) {
    this(ValidationResultWrapperJNI.new_DetailedValidationResult__SWIG_1(n, SWIGTYPE_p_std__shared_ptrT_ValidationResult_t.getCPtr(r)), true);
  }

}
