/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class EncryptionHelperWrapperJNI {
  public final static native long getKeysPair();
  public final static native String getPublicKey(long jarg1);
  public final static native String getPrivateKey(long jarg1);
  public final static native long encryptAsymmetric(String jarg1, String jarg2);
  public final static native String decryptAsymmetric(long jarg1, String jarg2);
  public final static native long createSignature(String jarg1, String jarg2);
  public final static native boolean verifySignature(String jarg1, long jarg2, String jarg3);
  public final static native String getCipherKey();
  public final static native long encryptSymmetric(String jarg1, String jarg2);
  public final static native String decryptSymmetric(long jarg1, String jarg2);
}
