/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class FieldsChanges {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FieldsChanges(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FieldsChanges obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FieldHelperWrapperJNI.delete_FieldsChanges(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FieldsChanges() {
    this(FieldHelperWrapperJNI.new_FieldsChanges__SWIG_0(), true);
  }

  public FieldsChanges(SWIGTYPE_p_StringList newFieldsUUID, SWIGTYPE_p_StringList updatedFieldsUUID, SWIGTYPE_p_StringList removedFieldsUUID) {
    this(FieldHelperWrapperJNI.new_FieldsChanges__SWIG_1(SWIGTYPE_p_StringList.getCPtr(newFieldsUUID), SWIGTYPE_p_StringList.getCPtr(updatedFieldsUUID), SWIGTYPE_p_StringList.getCPtr(removedFieldsUUID)), true);
  }

  public SWIGTYPE_p_StringList newFieldsUUID() {
    return new SWIGTYPE_p_StringList(FieldHelperWrapperJNI.FieldsChanges_newFieldsUUID(swigCPtr, this), false);
  }

  public SWIGTYPE_p_StringList updatedFieldsUUID() {
    return new SWIGTYPE_p_StringList(FieldHelperWrapperJNI.FieldsChanges_updatedFieldsUUID(swigCPtr, this), false);
  }

  public SWIGTYPE_p_StringList removedFieldsUUID() {
    return new SWIGTYPE_p_StringList(FieldHelperWrapperJNI.FieldsChanges_removedFieldsUUID(swigCPtr, this), false);
  }

}
