/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class FieldHelperWrapperJNI {
  public final static native long new_FieldsChanges__SWIG_0();
  public final static native long new_FieldsChanges__SWIG_1(long jarg1, long jarg2, long jarg3);
  public final static native long FieldsChanges_newFieldsUUID(long jarg1, FieldsChanges jarg1_);
  public final static native long FieldsChanges_updatedFieldsUUID(long jarg1, FieldsChanges jarg1_);
  public final static native long FieldsChanges_removedFieldsUUID(long jarg1, FieldsChanges jarg1_);
  public final static native void delete_FieldsChanges(long jarg1);
  public final static native boolean haveSameFieldValue__SWIG_0(long jarg1, long jarg2, long jarg3);
  public final static native boolean haveSameFieldValue__SWIG_1(long jarg1, long jarg2);
  public final static native boolean varsAreSubset(long jarg1, long jarg2);
  public final static native long copyFields(long jarg1, long jarg2);
  public final static native long getFieldsChanges(long jarg1, long jarg2);
}
