/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class FieldValidatorWrapperJNI {
  public final static native long FieldValidator_validate(long jarg1, FieldValidator jarg1_, long jarg2);
  public final static native long FieldValidator_validateBasicField(long jarg1, FieldValidator jarg1_, long jarg2);
  public final static native long FieldValidator_validateSocial(long jarg1, FieldValidator jarg1_, long jarg2);
  public final static native long FieldValidator_validateDuplication(long jarg1, FieldValidator jarg1_, long jarg2);
  public final static native long new_FieldValidator();
  public final static native void delete_FieldValidator(long jarg1);
}
