/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class FieldHelperWrapper {
  public static boolean haveSameFieldValue(SWIGTYPE_p_FieldList fieldsList1, SWIGTYPE_p_FieldList fieldsList2, SWIGTYPE_p_FieldCategory cat) {
    return FieldHelperWrapperJNI.haveSameFieldValue__SWIG_0(SWIGTYPE_p_FieldList.getCPtr(fieldsList1), SWIGTYPE_p_FieldList.getCPtr(fieldsList2), SWIGTYPE_p_FieldCategory.getCPtr(cat));
  }

  public static boolean haveSameFieldValue(SWIGTYPE_p_FieldList fieldsList1, SWIGTYPE_p_FieldList fieldsList2) {
    return FieldHelperWrapperJNI.haveSameFieldValue__SWIG_1(SWIGTYPE_p_FieldList.getCPtr(fieldsList1), SWIGTYPE_p_FieldList.getCPtr(fieldsList2));
  }

  public static boolean varsAreSubset(SWIGTYPE_p_FieldList left, SWIGTYPE_p_FieldList right) {
    return FieldHelperWrapperJNI.varsAreSubset(SWIGTYPE_p_FieldList.getCPtr(left), SWIGTYPE_p_FieldList.getCPtr(right));
  }

  public static SWIGTYPE_p_IBaseModel copyFields(SWIGTYPE_p_IBaseModel fromModel, SWIGTYPE_p_IBaseModel toModel) {
    long cPtr = FieldHelperWrapperJNI.copyFields(SWIGTYPE_p_IBaseModel.getCPtr(fromModel), SWIGTYPE_p_IBaseModel.getCPtr(toModel));
    return (cPtr == 0) ? null : new SWIGTYPE_p_IBaseModel(cPtr, false);
  }

  public static SWIGTYPE_p_FieldsChangesPtr getFieldsChanges(SWIGTYPE_p_FieldList oldState, SWIGTYPE_p_FieldList newState) {
    return new SWIGTYPE_p_FieldsChangesPtr(FieldHelperWrapperJNI.getFieldsChanges(SWIGTYPE_p_FieldList.getCPtr(oldState), SWIGTYPE_p_FieldList.getCPtr(newState)), true);
  }

}
