/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class FieldsValidatorResult extends ValidationResult {
  private transient long swigCPtr;

  protected FieldsValidatorResult(long cPtr, boolean cMemoryOwn) {
    super(ValidationResultWrapperJNI.FieldsValidatorResult_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FieldsValidatorResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ValidationResultWrapperJNI.delete_FieldsValidatorResult(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FieldsValidatorResult(SWIGTYPE_p_std__shared_ptrT_ValidationResult_t validationResult, SWIGTYPE_p_std__shared_ptrT_FieldsChanges_t fieldsChanges) {
    this(ValidationResultWrapperJNI.new_FieldsValidatorResult(SWIGTYPE_p_std__shared_ptrT_ValidationResult_t.getCPtr(validationResult), SWIGTYPE_p_std__shared_ptrT_FieldsChanges_t.getCPtr(fieldsChanges)), true);
  }

}
