/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class FieldWrapperJNI {
  public final static native long new_Field__SWIG_0(String jarg1, String jarg2, long jarg3);
  public final static native long new_Field__SWIG_1(String jarg1, long jarg2, String jarg3, long jarg4);
  public final static native long new_Field__SWIG_2(String jarg1, long jarg2, String jarg3);
  public final static native long new_Field__SWIG_3(long jarg1, String jarg2, long jarg3);
  public final static native long new_Field__SWIG_4(long jarg1, String jarg2);
  public final static native long new_Field__SWIG_5(String jarg1, String jarg2, String jarg3, long jarg4);
  public final static native long new_Field__SWIG_6(String jarg1, String jarg2, long jarg3, String jarg4);
  public final static native long new_Field__SWIG_7(String jarg1, String jarg2);
  public final static native long new_Field__SWIG_8();
  public final static native String Field_categoryName(long jarg1, Field jarg1_);
  public final static native void Field_setCategory(long jarg1, Field jarg1_, long jarg2);
  public final static native String Field_value(long jarg1, Field jarg1_);
  public final static native void Field_setValue(long jarg1, Field jarg1_, String jarg2);
  public final static native long Field_category(long jarg1, Field jarg1_);
  public final static native String Field_countryCodeConflictState(long jarg1, Field jarg1_);
  public final static native void Field_setCountryCodeConflictState(long jarg1, Field jarg1_, String jarg2);
  public final static native boolean Field_conflict(long jarg1, Field jarg1_);
  public final static native int Field_hashCode(long jarg1, Field jarg1_);
  public final static native boolean Field_equals(long jarg1, Field jarg1_, long jarg2);
  public final static native void Field_setCloudVerified(long jarg1, Field jarg1_, boolean jarg2);
  public final static native boolean Field_cloudVerified(long jarg1, Field jarg1_);
  public final static native void Field_setFromContact(long jarg1, Field jarg1_, boolean jarg2);
  public final static native void Field_setHidden(long jarg1, Field jarg1_, boolean jarg2);
  public final static native void Field_setSocialType(long jarg1, Field jarg1_, String jarg2);
  public final static native String Field_socialType(long jarg1, Field jarg1_);
  public final static native void Field_setObjectId(long jarg1, Field jarg1_, String jarg2);
  public final static native String Field_objectId(long jarg1, Field jarg1_);
  public final static native void Field_setLabel(long jarg1, Field jarg1_, String jarg2);
  public final static native String Field_label(long jarg1, Field jarg1_);
  public final static native void Field_setParentUuid(long jarg1, Field jarg1_, String jarg2);
  public final static native String Field_parentUuid(long jarg1, Field jarg1_);
  public final static native void Field_linkedUuidsAdd(long jarg1, Field jarg1_, long jarg2);
  public final static native long Field_linkedUuids(long jarg1, Field jarg1_);
  public final static native void Field_setVerified(long jarg1, Field jarg1_, boolean jarg2);
  public final static native boolean Field_verified(long jarg1, Field jarg1_);
  public final static native void Field_setPreferred(long jarg1, Field jarg1_, boolean jarg2);
  public final static native boolean Field_preferred(long jarg1, Field jarg1_);
  public final static native int Field_rowId(long jarg1, Field jarg1_);
  public final static native String Field_ownerUuid(long jarg1, Field jarg1_);
  public final static native int Field_sequence(long jarg1, Field jarg1_);
  public final static native String Field_calculateModelHash(long jarg1, Field jarg1_);
  public final static native String Field_toJson(long jarg1, Field jarg1_);
  public final static native long Field_toJsonObj(long jarg1, Field jarg1_);
  public final static native long Field_build__SWIG_0(long jarg1);
  public final static native long Field_build__SWIG_1(long jarg1);
  public final static native long Field_build__SWIG_2(long jarg1, String jarg2);
  public final static native long Field_build__SWIG_3(String jarg1, String jarg2);
  public final static native long Field_fromJson__SWIG_0(String jarg1);
  public final static native long Field_fromJson__SWIG_1(long jarg1);
  public final static native boolean Field_haveFieldWithValue(long jarg1, long jarg2, String jarg3);
  public final static native boolean Field_haveNoVars(long jarg1);
  public final static native long Field_findByCategory(long jarg1, long jarg2);
  public final static native long Field_findSame(long jarg1, long jarg2);
  public final static native long Field_findByCategoryAndValue(long jarg1, long jarg2, String jarg3, String jarg4);
  public final static native long Field_findAllByCategory(long jarg1, long jarg2);
  public final static native boolean Field_containsCommon(long jarg1, long jarg2);
  public final static native long Field_findAllByCategories(long jarg1, long jarg2);
  public final static native void Field_remove(long jarg1, long jarg2);
  public final static native void delete_Field(long jarg1);
}
