/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class HashServiceWrapper {
  public static String calculateListHash(SWIGTYPE_p_StringList values) {
    return HashServiceWrapperJNI.calculateListHash(SWIGTYPE_p_StringList.getCPtr(values));
  }

  public static String calculateValueHash(String value) {
    return HashServiceWrapperJNI.calculateValueHash(value);
  }

}
