/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class LibPhoneWrapperJNI {
  public final static native boolean isPhoneValid(String jarg1);
  public final static native boolean hasCountryCode(String jarg1);
  public final static native String formatE164(String jarg1);
  public final static native boolean isFixedLineValid(String jarg1);
  public final static native boolean isMobilePhoneValid(String jarg1);
  public final static native boolean validateMobilePhone(String jarg1);
  public final static native String getWithoutCode(String jarg1);
  public final static native String getCountryCode(String jarg1);
}
