/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class Md5UtilWrapper {
  public static String computeMD5List(SWIGTYPE_p_StringList strings) {
    return Md5UtilWrapperJNI.computeMD5List(SWIGTYPE_p_StringList.getCPtr(strings));
  }

  public static String computeMD5(String message) {
    return Md5UtilWrapperJNI.computeMD5(message);
  }

}
