/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class Md5UtilWrapperJNI {
  public final static native String computeMD5List(long jarg1);
  public final static native String computeMD5(String jarg1);
}
