/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ProfileValidatorWrapperJNI {
  public final static native long ProfileValidator_validate(long jarg1, ProfileValidator jarg1_, long jarg2);
  public final static native long ProfileValidator_validatePair(long jarg1, ProfileValidator jarg1_, long jarg2, long jarg3);
  public final static native long ProfileValidator_validateField(long jarg1, ProfileValidator jarg1_, long jarg2, long jarg3);
  public final static native long new_ProfileValidator();
  public final static native void delete_ProfileValidator(long jarg1);
}
