/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ProfileWrapperJNI {
  public final static native long new_Profile__SWIG_0(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5, long jarg6);
  public final static native long new_Profile__SWIG_1(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native long new_Profile__SWIG_2(String jarg1, String jarg2, String jarg3, String jarg4, long jarg5);
  public final static native long new_Profile__SWIG_3();
  public final static native String Profile_name(long jarg1, Profile jarg1_);
  public final static native void Profile_setName(long jarg1, Profile jarg1_, String jarg2);
  public final static native String Profile_prefix(long jarg1, Profile jarg1_);
  public final static native void Profile_setPrefix(long jarg1, Profile jarg1_, String jarg2);
  public final static native String Profile_avatar(long jarg1, Profile jarg1_);
  public final static native void Profile_setAvatar(long jarg1, Profile jarg1_, String jarg2);
  public final static native String Profile_accountType(long jarg1, Profile jarg1_);
  public final static native void Profile_setAccountType(long jarg1, Profile jarg1_, String jarg2);
  public final static native String Profile_publicKey(long jarg1, Profile jarg1_);
  public final static native void Profile_setPublicKey(long jarg1, Profile jarg1_, String jarg2);
  public final static native String Profile_privateKey(long jarg1, Profile jarg1_);
  public final static native long Profile_signInTypes(long jarg1, Profile jarg1_);
  public final static native String Profile_toJson(long jarg1, Profile jarg1_);
  public final static native long Profile_toJsonObj(long jarg1, Profile jarg1_);
  public final static native String Profile_calculateModelHash(long jarg1, Profile jarg1_);
  public final static native boolean Profile_equals(long jarg1, Profile jarg1_, long jarg2, Profile jarg2_);
  public final static native int Profile_hashCode(long jarg1, Profile jarg1_);
  public final static native long Profile_build();
  public final static native long Profile_fromJson__SWIG_0(String jarg1);
  public final static native long Profile_fromJson__SWIG_1(long jarg1);
  public final static native void delete_Profile(long jarg1);
}
