/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ProfileValidator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ProfileValidator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProfileValidator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ProfileValidatorWrapperJNI.delete_ProfileValidator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_ValidationResultPtr validate(SWIGTYPE_p_ProfilePtr value) {
    return new SWIGTYPE_p_ValidationResultPtr(ProfileValidatorWrapperJNI.ProfileValidator_validate(swigCPtr, this, SWIGTYPE_p_ProfilePtr.getCPtr(value)), true);
  }

  public SWIGTYPE_p_FieldsValidatorResultPtr validatePair(SWIGTYPE_p_ProfilePtr originalProfile, SWIGTYPE_p_ProfilePtr modifiedProfile) {
    return new SWIGTYPE_p_FieldsValidatorResultPtr(ProfileValidatorWrapperJNI.ProfileValidator_validatePair(swigCPtr, this, SWIGTYPE_p_ProfilePtr.getCPtr(originalProfile), SWIGTYPE_p_ProfilePtr.getCPtr(modifiedProfile)), true);
  }

  public SWIGTYPE_p_ValidationResultPtr validateField(SWIGTYPE_p_FieldPtr field, SWIGTYPE_p_ProfilePtr profile) {
    return new SWIGTYPE_p_ValidationResultPtr(ProfileValidatorWrapperJNI.ProfileValidator_validateField(swigCPtr, this, SWIGTYPE_p_FieldPtr.getCPtr(field), SWIGTYPE_p_ProfilePtr.getCPtr(profile)), true);
  }

  public ProfileValidator() {
    this(ProfileValidatorWrapperJNI.new_ProfileValidator(), true);
  }

}
