/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ReceivedCardWrapperJNI {
  public final static native long new_ReceivedCard__SWIG_0(String jarg1, long jarg2, String jarg3);
  public final static native long new_ReceivedCard__SWIG_1(String jarg1, long jarg2, String jarg3, long jarg4);
  public final static native long new_ReceivedCard__SWIG_2(long jarg1, String jarg2, long jarg3);
  public final static native long new_ReceivedCard__SWIG_3();
  public final static native boolean ReceivedCard_canUseOwnPhoto(long jarg1, ReceivedCard jarg1_);
  public final static native boolean ReceivedCard_canUseOwnName(long jarg1, ReceivedCard jarg1_);
  public final static native boolean ReceivedCard_canModifyMobilePhones(long jarg1, ReceivedCard jarg1_);
  public final static native boolean ReceivedCard_privateCard(long jarg1, ReceivedCard jarg1_);
  public final static native String ReceivedCard_ownerKey(long jarg1, ReceivedCard jarg1_);
  public final static native String ReceivedCard_employeeCardUuid(long jarg1, ReceivedCard jarg1_);
  public final static native String ReceivedCard_employeeCardOwnerUuid(long jarg1, ReceivedCard jarg1_);
  public final static native String ReceivedCard_status(long jarg1, ReceivedCard jarg1_);
  public final static native long ReceivedCard_merchant(long jarg1, ReceivedCard jarg1_);
  public final static native String ReceivedCard_calculateModelHash(long jarg1, ReceivedCard jarg1_);
  public final static native String ReceivedCard_toJson(long jarg1, ReceivedCard jarg1_);
  public final static native long ReceivedCard_toJsonObj(long jarg1, ReceivedCard jarg1_);
  public final static native long ReceivedCard_fromJson__SWIG_0(String jarg1);
  public final static native long ReceivedCard_fromJson__SWIG_1(long jarg1);
  public final static native void delete_ReceivedCard(long jarg1);
}
