/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ReceivedCard {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ReceivedCard(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReceivedCard obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ReceivedCardWrapperJNI.delete_ReceivedCard(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ReceivedCard(String uuid, SWIGTYPE_p_FieldList fields, String name) {
    this(ReceivedCardWrapperJNI.new_ReceivedCard__SWIG_0(uuid, SWIGTYPE_p_FieldList.getCPtr(fields), name), true);
  }

  public ReceivedCard(String uuid, SWIGTYPE_p_FieldList fields, String name, SWIGTYPE_p_ProfilePtr profile) {
    this(ReceivedCardWrapperJNI.new_ReceivedCard__SWIG_1(uuid, SWIGTYPE_p_FieldList.getCPtr(fields), name, SWIGTYPE_p_ProfilePtr.getCPtr(profile)), true);
  }

  public ReceivedCard(SWIGTYPE_p_FieldList fields, String name, SWIGTYPE_p_ProfilePtr profile) {
    this(ReceivedCardWrapperJNI.new_ReceivedCard__SWIG_2(SWIGTYPE_p_FieldList.getCPtr(fields), name, SWIGTYPE_p_ProfilePtr.getCPtr(profile)), true);
  }

  public ReceivedCard() {
    this(ReceivedCardWrapperJNI.new_ReceivedCard__SWIG_3(), true);
  }

  public boolean canUseOwnPhoto() {
    return ReceivedCardWrapperJNI.ReceivedCard_canUseOwnPhoto(swigCPtr, this);
  }

  public boolean canUseOwnName() {
    return ReceivedCardWrapperJNI.ReceivedCard_canUseOwnName(swigCPtr, this);
  }

  public boolean canModifyMobilePhones() {
    return ReceivedCardWrapperJNI.ReceivedCard_canModifyMobilePhones(swigCPtr, this);
  }

  public boolean privateCard() {
    return ReceivedCardWrapperJNI.ReceivedCard_privateCard(swigCPtr, this);
  }

  public String ownerKey() {
    return ReceivedCardWrapperJNI.ReceivedCard_ownerKey(swigCPtr, this);
  }

  public String employeeCardUuid() {
    return ReceivedCardWrapperJNI.ReceivedCard_employeeCardUuid(swigCPtr, this);
  }

  public String employeeCardOwnerUuid() {
    return ReceivedCardWrapperJNI.ReceivedCard_employeeCardOwnerUuid(swigCPtr, this);
  }

  public String status() {
    return ReceivedCardWrapperJNI.ReceivedCard_status(swigCPtr, this);
  }

  public SWIGTYPE_p_ProfilePtr merchant() {
    return new SWIGTYPE_p_ProfilePtr(ReceivedCardWrapperJNI.ReceivedCard_merchant(swigCPtr, this), true);
  }

  public String calculateModelHash() {
    return ReceivedCardWrapperJNI.ReceivedCard_calculateModelHash(swigCPtr, this);
  }

  public String toJson() {
    return ReceivedCardWrapperJNI.ReceivedCard_toJson(swigCPtr, this);
  }

  public SWIGTYPE_p_json11__Json toJsonObj() {
    return new SWIGTYPE_p_json11__Json(ReceivedCardWrapperJNI.ReceivedCard_toJsonObj(swigCPtr, this), true);
  }

  public static SWIGTYPE_p_std__shared_ptrT_ReceivedCard_t fromJson(String jsonString) {
    return new SWIGTYPE_p_std__shared_ptrT_ReceivedCard_t(ReceivedCardWrapperJNI.ReceivedCard_fromJson__SWIG_0(jsonString), true);
  }

  public static SWIGTYPE_p_std__shared_ptrT_ReceivedCard_t fromJson(SWIGTYPE_p_json11__Json jsonObj) {
    return new SWIGTYPE_p_std__shared_ptrT_ReceivedCard_t(ReceivedCardWrapperJNI.ReceivedCard_fromJson__SWIG_1(SWIGTYPE_p_json11__Json.getCPtr(jsonObj)), true);
  }

}
