/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class StringValidator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StringValidator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringValidator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StringValidatorWrapperJNI.delete_StringValidator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_ValidationResultPtr validate(SWIGTYPE_p_StringPtr value) {
    return new SWIGTYPE_p_ValidationResultPtr(StringValidatorWrapperJNI.StringValidator_validate__SWIG_0(swigCPtr, this, SWIGTYPE_p_StringPtr.getCPtr(value)), true);
  }

  public SWIGTYPE_p_ValidationResultPtr validate(SWIGTYPE_p_StringPtr value, StringValidatorOptions options) {
    return new SWIGTYPE_p_ValidationResultPtr(StringValidatorWrapperJNI.StringValidator_validate__SWIG_1(swigCPtr, this, SWIGTYPE_p_StringPtr.getCPtr(value), StringValidatorOptions.getCPtr(options), options), true);
  }

  public StringValidator() {
    this(StringValidatorWrapperJNI.new_StringValidator(), true);
  }

}
