/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class StringValidatorWrapperJNI {
  public final static native long new_StringValidatorOptions(long jarg1, boolean jarg2, String jarg3);
  public final static native void StringValidatorOptions_limit_set(long jarg1, StringValidatorOptions jarg1_, long jarg2);
  public final static native long StringValidatorOptions_limit_get(long jarg1, StringValidatorOptions jarg1_);
  public final static native void StringValidatorOptions_allowBlank_set(long jarg1, StringValidatorOptions jarg1_, boolean jarg2);
  public final static native boolean StringValidatorOptions_allowBlank_get(long jarg1, StringValidatorOptions jarg1_);
  public final static native void StringValidatorOptions_regexTemplate_set(long jarg1, StringValidatorOptions jarg1_, String jarg2);
  public final static native String StringValidatorOptions_regexTemplate_get(long jarg1, StringValidatorOptions jarg1_);
  public final static native void delete_StringValidatorOptions(long jarg1);
  public final static native long StringValidator_validate__SWIG_0(long jarg1, StringValidator jarg1_, long jarg2);
  public final static native long StringValidator_validate__SWIG_1(long jarg1, StringValidator jarg1_, long jarg2, long jarg3, StringValidatorOptions jarg3_);
  public final static native long new_StringValidator();
  public final static native void delete_StringValidator(long jarg1);
}
