/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ValidationResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ValidationResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ValidationResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ValidationResultWrapperJNI.delete_ValidationResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ValidationResult(boolean isValid) {
    this(ValidationResultWrapperJNI.new_ValidationResult__SWIG_0(isValid), true);
  }

  public ValidationResult(boolean isValid, String fieldUUID) {
    this(ValidationResultWrapperJNI.new_ValidationResult__SWIG_1(isValid, fieldUUID), true);
  }

  public ValidationResult(boolean isValid, SWIGTYPE_p_std__listT_std__shared_ptrT_DetailedValidationResult_t_t details, String fieldUUID) {
    this(ValidationResultWrapperJNI.new_ValidationResult__SWIG_2(isValid, SWIGTYPE_p_std__listT_std__shared_ptrT_DetailedValidationResult_t_t.getCPtr(details), fieldUUID), true);
  }

  public ValidationResult() {
    this(ValidationResultWrapperJNI.new_ValidationResult__SWIG_3(), true);
  }

  public SWIGTYPE_p_std__shared_ptrT_ValidationResult_t getByName(String name) {
    return new SWIGTYPE_p_std__shared_ptrT_ValidationResult_t(ValidationResultWrapperJNI.ValidationResult_getByName(swigCPtr, this, name), true);
  }

  public SWIGTYPE_p_std__shared_ptrT_ValidationResult_t getByUuid(String uuid) {
    return new SWIGTYPE_p_std__shared_ptrT_ValidationResult_t(ValidationResultWrapperJNI.ValidationResult_getByUuid(swigCPtr, this, uuid), true);
  }

  public SWIGTYPE_p_StringList getInvalidFieldsUuid() {
    return new SWIGTYPE_p_StringList(ValidationResultWrapperJNI.ValidationResult_getInvalidFieldsUuid(swigCPtr, this), true);
  }

  public boolean haveUnskippableConflicts() {
    return ValidationResultWrapperJNI.ValidationResult_haveUnskippableConflicts(swigCPtr, this);
  }

  public void addError(String error) {
    ValidationResultWrapperJNI.ValidationResult_addError(swigCPtr, this, error);
  }

  public void revalidate() {
    ValidationResultWrapperJNI.ValidationResult_revalidate(swigCPtr, this);
  }

  public String fieldUuid() {
    return ValidationResultWrapperJNI.ValidationResult_fieldUuid(swigCPtr, this);
  }

  public void setFieldUUID(String uuid) {
    ValidationResultWrapperJNI.ValidationResult_setFieldUUID(swigCPtr, this, uuid);
  }

  public SWIGTYPE_p_StringList errors() {
    return new SWIGTYPE_p_StringList(ValidationResultWrapperJNI.ValidationResult_errors(swigCPtr, this), false);
  }

  public void errorsAdd(SWIGTYPE_p_StringList other) {
    ValidationResultWrapperJNI.ValidationResult_errorsAdd(swigCPtr, this, SWIGTYPE_p_StringList.getCPtr(other));
  }

  public boolean isValid() {
    return ValidationResultWrapperJNI.ValidationResult_isValid(swigCPtr, this);
  }

  public void setIsValid(boolean isValid) {
    ValidationResultWrapperJNI.ValidationResult_setIsValid(swigCPtr, this, isValid);
  }

  public SWIGTYPE_p_std__listT_std__shared_ptrT_DetailedValidationResult_t_t details() {
    return new SWIGTYPE_p_std__listT_std__shared_ptrT_DetailedValidationResult_t_t(ValidationResultWrapperJNI.ValidationResult_details(swigCPtr, this), false);
  }

}
