/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brain.core;

public class ValidationResultWrapper {
  public static SWIGTYPE_p_std__shared_ptrT_ValidationResult_t combine(SWIGTYPE_p_std__listT_std__shared_ptrT_ValidationResult_t_t validationResults) {
    return new SWIGTYPE_p_std__shared_ptrT_ValidationResult_t(ValidationResultWrapperJNI.combine(SWIGTYPE_p_std__listT_std__shared_ptrT_ValidationResult_t_t.getCPtr(validationResults)), true);
  }

  public static SWIGTYPE_p_std__shared_ptrT_ValidationResult_t combineDetails(SWIGTYPE_p_std__listT_std__shared_ptrT_ValidationResult_t_t validationResults) {
    return new SWIGTYPE_p_std__shared_ptrT_ValidationResult_t(ValidationResultWrapperJNI.combineDetails(SWIGTYPE_p_std__listT_std__shared_ptrT_ValidationResult_t_t.getCPtr(validationResults)), true);
  }

}
